# Importing used libraries

In [28]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import VarianceThreshold

## reading data and split it

In [4]:
data=pd.read_csv(r"D:\semester 7\computiona;\sec\dataset_1.csv")

In [18]:
print(f"The shape of data is {data.shape}\n")
data.head()

The shape of data is (50000, 301)

,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,var_9,var_10,...,var_292,var_293,var_294,var_295,var_296,var_297,var_298,var_299,var_300,target
0,0,0,0.0,0.00,0.0,0,0,0,0,0,...,0.0,0,0,0,0,0,0,0.0,0.0000,0
1,0,0,0.0,3.00,0.0,0,0,0,0,0,...,0.0,0,0,0,0,0,0,0.0,0.0000,0
2,0,0,0.0,5.88,0.0,0,0,0,0,0,...,0.0,0,0,3,0,0,0,0.0,67772.7216,0
3,0,0,0.0,14.10,0.0,0,0,0,0,0,...,0.0,0,0,0,0,0,0,0.0,0.0000,0
4,0,0,0.0,5.76,0.0,0,0,0,0,0,...,0.0,0,0,0,0,0,0,0.0,0.0000,0

In [20]:
# we will examine features only on training data set to avoid overfitting

In [83]:
X_train,X_test,y_teain,y_test=train_test_split(
    data.drop(labels=['target'],axis=1),
    data['target'],
    test_size=.3,
    random_state=42
)
print(f"The shape of traninig data is : {X_train.shape}")
print(f"\nThe shape of testing data is : {X_test.shape}")

The shape of traninig data is : (35000, 300)

The shape of testing data is : (15000, 300)

# Applying Variance Threshold (scikit-learn)

In this step, we apply the **Variance Threshold** technique from the `sklearn.feature_selection` module to detect and remove **zero-variance features**.


After fitting the selector, the `get_support()` method is used to identify **which features are selected and which are removed** based on the variance threshold.

In [85]:
selecte=VarianceThreshold(threshold=0)
selecte.fit(X_train)

VarianceThreshold(threshold=0)

In [87]:
print(sum(selecte.get_support()))

258

In [89]:
# numer of removed_features 
costant_features=X_train.columns[~selecte.get_support()]
len(costant_features)

42

In [91]:
print("the Zero_variance columns are : \n")
costant_features

the Zero_variance columns are :

Index(['var_14', 'var_23', 'var_33', 'var_34', 'var_44', 'var_61', 'var_66',
       'var_67', 'var_69', 'var_73', 'var_80', 'var_81', 'var_87', 'var_89',
       'var_92', 'var_97', 'var_99', 'var_112', 'var_113', 'var_120',
       'var_122', 'var_127', 'var_129', 'var_135', 'var_158', 'var_167',
       'var_171', 'var_178', 'var_180', 'var_182', 'var_183', 'var_195',
       'var_196', 'var_201', 'var_212', 'var_215', 'var_225', 'var_227',
       'var_248', 'var_287', 'var_294', 'var_297'],
      dtype='str')

In [93]:
# to prof our cliam that zero variance is the constant feature
for col in costant_features:
    print(col,X_train[col].unique())

var_14 [0]
var_23 [0]
var_33 [0]
var_34 [0]
var_44 [0]
var_61 [0]
var_66 [0]
var_67 [0]
var_69 [0]
var_73 [0]
var_80 [0]
var_81 [0]
var_87 [0]
var_89 [0.]
var_92 [0]
var_97 [0]
var_99 [0]
var_112 [0]
var_113 [0]
var_120 [0]
var_122 [0]
var_127 [0]
var_129 [0]
var_135 [0]
var_158 [0]
var_167 [0]
var_171 [0]
var_178 [0.]
var_180 [0.]
var_182 [0]
var_183 [0]
var_195 [0]
var_196 [0]
var_201 [0]
var_212 [0]
var_215 [0]
var_225 [0]
var_227 [0.]
var_248 [0]
var_287 [0]
var_294 [0]
var_297 [0]

In [95]:
X_train

,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,var_9,var_10,...,var_291,var_292,var_293,var_294,var_295,var_296,var_297,var_298,var_299,var_300
38094,0,0,0.0,2.94,0.0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
40624,0,0,0.0,0.00,0.0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
49425,0,0,0.0,0.00,0.0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
35734,0,0,0.0,5.88,0.0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
41708,0,0,0.0,0.00,0.0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,0,0,0.0,5.46,0.0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
44732,0,0,0.0,0.00,0.0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
38158,0,0,0.0,2.94,0.0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
860,0,0,0.0,2.94,0.0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0.0,0.0
15795,0,0,0.0,8.55,0.0,0,0,0,0,0,...,0,0.0,0,0,0,3,0,0,0.0,0.0

### Removing the zero variance features on `X_train` and `X_test`

In [98]:
# get columns fame 
features_name=X_train.columns[selecte.get_support()]

In [100]:
X_train=selecte.transform(X_train)
X_test=selecte.transform(X_test)
print(f"the shape of X_train is {X_train.shape} \nand the X_test shape is {X_test.shape}")

the shape of X_train is (35000, 258)
and the X_test shape is (15000, 258)

In [104]:
# Transform rturne numpy array
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(35000, 258))

In [108]:
# retrieve it as a data frame
X_train=pd.DataFrame(X_train,columns=features_name)
X_train.head()

,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,var_9,var_10,...,var_289,var_290,var_291,var_292,var_293,var_295,var_296,var_298,var_299,var_300
0,0.0,0.0,0.0,2.94,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,5.88,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [112]:
print(f"we removed non effective column its number is {data.shape[1]-X_train.shape[1]}")

we removed non effective column its number is 43